// import { Inter } from "next/font/google";
import "./globals.css";
import SmoothScrolling from "./_components/SmoothScrolling.jsx";
import Head from "next/head";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "staicu, viviana",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      
      <Head>
        <link rel="icon" type="image/svg+xml" href="portfolio/public/assets/images/apple.svg" />
        <title>{metadata.title}</title>
      </Head>
      <body className="flex flex-col min-h-screen justify-between p-2">
        <SmoothScrolling>
          {children}
        </SmoothScrolling>
      </body>
      
    </html>

  );
}
