// import { Inter } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="portfolio/public/assets/images/apple.svg" />
        <title>staicu, viviana</title>
      </head>
      <body className="flex flex-col min-h-screen justify-between p-2">
        {children}
      </body>
    </html>
  );
}
