// A separate file with items (url should contain a link for each image)
export const items = [
  {
    id: "cloudsspaceship",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi088-colorcorrected-compress.jpeg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "blackbg1",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi078-blackbg.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "112skull",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi084.jpg",
    category: "",
    categorySpecific: "",
  },

  {
    id: "blueman",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi081-tablebg-blue.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "charcoalbrushREMOVE",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi082.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "irongiant",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi083.jpg",
    category: "",
    categorySpecific: "",
  },

  {
    id: "remoteREMOVE",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi085.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "fridgespaceship",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi087.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "3dDiagram",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi080.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "bluerobot",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi090.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "036",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/comp_036-throwcylinderinAir.jpg.webp",
    category: "sketch",
    categorySpecific: "",
  },
  {
    id: "043",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/comp_043.jpg.webp",
    category: "sketch",
    categorySpecific: "",
  },
  {
    id: "044",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/comp_044.jpg.webp",
    category: "sketch",
    categorySpecific: "",
  },

  {
    id: "054",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/comp_054.jpg.webp",
    category: "sketch",
    categorySpecific: "",
  },
  {
    id: "051",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/comp_051.jpg.webp",
    category: "sketch",
    categorySpecific: "",
  },

  {
    id: "defercoffeemachine",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi091.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "raffiMinasian-gatesfloor6",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi092.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "scifienvironments",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi022-5x7.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "handStudies",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi025-5x7.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "pmini-hand",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi026-5x7.jpg",
    category: "",
    categorySpecific: "",
  },

  {
    id: "035",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/comp_035.jpg.webp",
    category: "sketch",
    categorySpecific: "",
  },
  {
    id: "0471",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi047-5x7.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "0451",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi045-5x7.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "jellyfish004",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi004--5x7.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "jellyfish003",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi003-5x7.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "summerhandspencil",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi021-5x7.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "pittsburghhousebuildingarchitecture",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi023-5x7.jpg",
    category: "",
    categorySpecific: "",
  },

  // {
  //   id: "",
  //   name: "",
  //   url: "",
  //   category: "",
  //   categorySpecific: "",
  // },
  {
    id: "idk2",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/sketches/vivi079-blackbg-16-9.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "s1",
    name: "",
    url: "/imgs/sketchbook/compressed-0036.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "f1",
    name: "",
    url: "/imgs/sketchbook/neutronMachine-06499.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "f2",
    name: "",
    url: "/imgs/sketchbook/neutronMachine-06498.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "f3",
    name: "",
    url: "/imgs/sketchbook/neutronMachine-06496_large.jpg",
    category: "",
    categorySpecific: "",
  },

  {
    id: "f4",
    name: "",
    url: "/imgs/sketchbook/compressedFantasticalMachine-7497.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "b2",
    name: "",
    url: "/imgs/sketchbook/compressed-1483.jpg",
    category: "",
    categorySpecific: "",
  },

  {
    id: "s3",
    name: "",
    url: "/imgs/sketchbook/compressed-7194.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "s4",
    name: "",
    url: "/imgs/sketchbook/compressed-7738.jpg",
    category: "",
    categorySpecific: "",
  },

  {
    id: "b1",
    name: "",
    url: "/imgs/sketchbook/compressed-charoalMinis.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "charcoalPortrait-me",
    name: "charcoalPortrait-me",
    url: "/imgs/play/headEmptyCharcoal.jpg",
    category: "sketch",
    categorySpecific: "",
  },

  // {
  //   id: "",
  //   name: "",
  //   url: "",
  //   category: "sketch",
  //   categorySpecific: "",
  // },
];
