// A separate file with items (url should contain a link for each image)
export const items = [
  {
    id: "s1",
    name: "",
    url: "/imgs/sketchbook/compressed-0036.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "s2",
    name: "",
    url: "/imgs/sketchbook/compressed-0033.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "f1",
    name: "",
    url: "/imgs/sketchbook/neutronMachine-06499.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "f2",
    name: "",
    url: "/imgs/sketchbook/neutronMachine-06498.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "f3",
    name: "",
    url: "/imgs/sketchbook/neutronMachine-06496_large.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "skullMountains",
    name: "skullMountains",
    url: "/imgs/play/thumb4_161-crop.jpg",
    category: "sketch",
    categorySpecific: "",
  },
  {
    id: "f4",
    name: "",
    url: "/imgs/sketchbook/compressedFantasticalMachine-7497.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "b2",
    name: "",
    url: "/imgs/sketchbook/compressed-1483.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "f5",
    name: "",
    url: "/imgs/sketchbook/compressedFantasticalMachine-27.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "s3",
    name: "",
    url: "/imgs/sketchbook/compressed-7194.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "s4",
    name: "",
    url: "/imgs/sketchbook/compressed-7738.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "s5",
    name: "",
    url: "/imgs/sketchbook/compressed-9420.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "s6",
    name: "",
    url: "/imgs/sketchbook/compressed-9503.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "s7",
    name: "",
    url: "/imgs/sketchbook/compressed-9645.jpg",
    category: "",
    categorySpecific: "",
  },

  {
    id: "b1",
    name: "",
    url: "/imgs/sketchbook/compressed-charoalMinis.jpg",
    category: "",
    categorySpecific: "",
  },
  {
    id: "charcoalPortrait-me",
    name: "charcoalPortrait-me",
    url: "/imgs/play/headEmptyCharcoal.jpg",
    category: "sketch",
    categorySpecific: "",
  },
];