// A separate file with items (url should contain a link for each image)
export const items = [
  {
    id: "xrCube",
    name: "XRcube",
    url: "https://image.mux.com/jysKZgic9HN6hv3xGk9QVJsFwdrKQvTZ0101ucmtqXPp00/animated.gif?width=320",
    category: "3d",
    fileType: "webp",
    categorySpecific: "",
  },
  {
    id: "spatula-01",
    name: "",
    url: "https://res.cloudinary.com/ddjxpkewq/image/upload/f_auto,q_auto/v1/play/lohb80s9ngarowqrs78s",
    category: "",
    fileType: "webp",
    categorySpecific: "",
  },
  {
    id: "guytouchdesigner",
    name: "",
    url: "https://image.mux.com/waB17xivBisJ48pkoUT3c1OCby00MZ9wIY3tEcJp5sCo/animated.gif",
    fileType: "webp",
    category: "3d",
    categorySpecific: "",
  },
  {
    id: "test-dohnut",
    name: "t1",
    url: "https://res.cloudinary.com/ddjxpkewq/video/upload/f_mp4,q_auto/v1/play/gla0hqfer8yzhpquznw2",
    fileType: "mp4",
    category: "3d",
    categorySpecific: "",
  },
  {
    id: "mestreet",
    name: "",
    url: "https://res.cloudinary.com/ddjxpkewq/image/upload/f_auto,q_auto/v1/play/b5sneesjednbid7rbne8",
    fileType: "webp",
    category: "photo",
    categorySpecific: "",
  },
  {
    id: "suanna-blur",
    name: "suanna-blur",
    url: "https://res.cloudinary.com/ddjxpkewq/image/upload/f_auto,q_auto/v1/play/xnnxzcswnzklx0d9mqf9",
    fileType: "webp",
    category: "photo",
    categorySpecific: "",
  },
  {
    id: "sf",
    name: "",
    url: "https://res.cloudinary.com/ddjxpkewq/image/upload/f_auto,q_auto/v1/play/pxqygk6j2mgvtj1agb9t",
    fileType: "webp",
    category: "photo",
    categorySpecific: "",
  },
  {
    id: "sf-tree",
    name: "",
    url: "https://res.cloudinary.com/ddjxpkewq/image/upload/f_auto,q_auto/v1/play/qaepgutursd01u5s0hgw",
    fileType: "webp",
    category: "photo",
    categorySpecific: "",
  },
  {
    id: "sf-hill",
    name: "",
    url: "https://res.cloudinary.com/ddjxpkewq/image/upload/f_auto,q_auto/v1/play/cdiy9zql0eds3kgfameb",
    fileType: "webp",
    category: "photo",
    categorySpecific: "",
  },
  {
    id: "uhh",
    name: "",
    url: "https://res.cloudinary.com/ddjxpkewq/image/upload/f_auto,q_auto/v1/play/bttxt1opxs4bcf4gvhga",
    fileType: "webp",
    category: "photo",
    categorySpecific: "",
  },
  {
    id: "getty",
    name: "",
    url: "https://res.cloudinary.com/ddjxpkewq/image/upload/f_auto,q_auto/v1/play/assjicmxoj5iacg071ah",
    fileType: "webp",
    category: "photo",
    categorySpecific: "",
  },

  // {
  //   id: "",
  //   name: "",
  //   url: "",
  //   fileType: "webp",
  //   category: "photo",
  //   categorySpecific: "",
  // },
  // {
  //   id: "",
  //   name: "",
  //   url: "",
  //   fileType: "webp",
  //   category: "photo",
  //   categorySpecific: "",
  // },
];