// A separate file with items (url should contain a link for each image)
export const items = [
  {
    id: "xrCube",
    name: "XRcube",
    url: "https://image.mux.com/jysKZgic9HN6hv3xGk9QVJsFwdrKQvTZ0101ucmtqXPp00/animated.gif?width=320",
    category: "3d",
    fileType: "webp",
    categorySpecific: "",
  },

  {
    id: "guytouchdesigner",
    name: "",
    url: "https://image.mux.com/waB17xivBisJ48pkoUT3c1OCby00MZ9wIY3tEcJp5sCo/animated.gif",
    fileType: "webp",
    category: "motion",
    categorySpecific: "",
  },
  {
    id: "lucyprada",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/lucy-2-prada.jpg",
    fileType: "webp",
    category: "photo",
    categorySpecific: "",
  },
  {
    id: "film-lightblur",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/3-vivianaFilm008.jpg",
    fileType: "webp",
    category: "photo",
  },
  {
    id: "plane-slog2",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_plane-slog2-shortest-reordered-trim.mov.webm",
    fileType: "webm",
    category: "video",
  },
  {
    id: "refridgerator",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/refrigerator-lut_1.2.1.jpg",
    fileType: "webp",
    category: "photo",
  },
  {
    id: "perryShoppingcart",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edited-00796-perry.jpg.webp",
    fileType: "webp",
    category: "photo",
    categorySpecific: "",
  },
  {
    id: "romaniagrass02",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_DSC09747_romania_grass.JPG.webp",
    fileType: "webp",
    category: "photo",
    categorySpecific: "",
  },
  {
    id: "romaniagrass01",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_DSC02981.JPG.webp",
    fileType: "webp",
    category: "photo",
    categorySpecific: "",
  },
  {
    id: "meSanDiego",
    name: "",
    url: "/compressed_edit-03512-3.webp",
    fileType: "webp",
    category: "photo",
    categorySpecific: "",
  },
  {
    id: "isdsdsdk",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/compressed_edit-03827.jpg.webp",
    fileType: "webp",
    category: "photo",
    categorySpecific: "",
  },
  {
    id: "wipedClean",
    name: "t1",
    url: "https://stream.mux.com/bWtOP7AxOvsonYYuecvDfLM00QVyHjZu8lIOvatm011bE.m3u8",
    fileType: "webm",
    category: "video",
    categorySpecific: "",
  },
  {
    id: "getty-video",
    name: "t1",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_getty-scene-01-trim.webm",
    fileType: "webm",
    category: "video",
    categorySpecific: "",
  },
  {
    id: "liminal-spin",
    name: "t1",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_lg-gif-spin.mov.webm",
    fileType: "webm",
    category: "code",
    categorySpecific: "",
  },
  {
    id: "td-dohnut",
    name: "td-tourus",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_111524_firstTouchdesignerTourus.mov.webm",
    fileType: "webm",
    category: "motion",
    categorySpecific: "",
  },

  {
    id: "me-standing-instreet",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edit-061.jpg.webp",
    fileType: "webp",
    category: "photo",
  },
  {
    id: "pfolio-computers",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_old-portfolio-home.png.webp",
    fileType: "webp",
    category: "code",
  },
  {
    id: "pmini-tabletop-sunset",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_DSC04957.JPG.webp",
    fileType: "webp",
    category: "photo",
  },
  {
    id: "tennis-running",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edit-01410.jpg.webp",
    fileType: "webp",
    category: "photo",
  },
  {
    id: "liminal-title",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_liminalTitle.png.webp",
    fileType: "webp",
    category: "3d",
  },

  {
    id: "aphi-dj",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_aphi-linkedin-4x5-instaFrame.jpg.webp",
    fileType: "webp",
    category: "photo",
  },
  {
    id: "gradientstudies",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_gradientStudies.jpg.webp",
    fileType: "webp",
    category: "graphic",
  },
  // {
  //   id: "aphi-blue-angry-girls",
  //   name: "",
  //   url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edit-02084.jpg.webp",
  //   fileType: "webp",
  //   category: "photo",
  // },
  {
    id: "sci-fi-render-vines-grass",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_sci-fi-render-01.jpg.webp",
    fileType: "webp",
    category: "3d",
  },
  {
    id: "suanna-standing-sanjose",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_comp_edit-highGrain-03897.jpg.webp.webp",
    fileType: "webp",
    category: "photo",
  },
  {
    id: "suanna-sanjose",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edit-05805.jpg.webp",
    fileType: "webp",
    category: "photo",
  },
  {
    id: "expression-charcoal-minis",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_expression-charcoal-minis.jpeg.webp",
    fileType: "webp",
    category: "sketch",
  },
  {
    id: "tree-sanjose",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edit-05879.jpg.webp",
    fileType: "webp",
    category: "photo",
  },
  {
    id: "tree-2-sanjose",
    name: "",
    url: "https://vstaicu-portfolio-assets.s3.us-east-2.amazonaws.com/play/comp_edit-05882.jpg.webp",
    fileType: "webp",
    category: "photo",
  },
  // {
  //   id: "getty",
  //   name: "",
  //   url: "https://res.cloudinary.com/ddjxpkewq/image/upload/f_auto,q_auto/v1/play/assjicmxoj5iacg071ah",
  //   fileType: "webp",
  //   category: "photo",
  //   categorySpecific: "",
  // },

  // {
  //   id: "",
  //   name: "",
  //   url: "",
  //   fileType: "webp",
  //   category: "photo",
  //   categorySpecific: "",
  // },
  // {
  //   id: "",
  //   name: "",
  //   url: "",
  //   fileType: "webp",
  //   category: "photo",
  //   categorySpecific: "",
  // },
];